# Site settings
title: Lwin Moe
email: admin@lwinmoe.org
description: > # this means to ignore newlines until "baseurl:"
  Lwin Moe is a computational linguist, and work at the LINGUIST List. He studied computer science and linguistics at Indiana University in Bloomington, Indiana University-Purdue University in Fort Wayne, Asian Institute of Technology in Bangkok.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lwinmoe.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include: ['_pages']

sass:
    style: compressed


